name: jokes_compose
description: User auth (login/register + sesión local) con Flutter + SQLite
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true